In [1]:
import numpy as np

In [2]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [3]:
a.T


array([[1, 4],
       [2, 5],
       [3, 6]])

In [4]:
a.T.ravel()

array([1, 4, 2, 5, 3, 6])

In [5]:
a.shape

(2, 3)

In [6]:
b = a.ravel()
b = b.reshape((2, 3))
b


array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
a.reshape((2, -1))    

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
b[0,0]=99

In [9]:
a

array([[99,  2,  3],
       [ 4,  5,  6]])

In [10]:
a=np.zeros((3,2))

In [11]:
b=a.T.reshape(3*2)

In [12]:
b[0]=9

In [13]:
a

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [14]:
z = np.array([1, 2, 3])
z

array([1, 2, 3])

In [15]:
z[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [16]:
z[np.newaxis, :]

array([[1, 2, 3]])

In [17]:
a = np.arange(4*3*2).reshape(4, 3, 2)
a.shape

(4, 3, 2)

In [18]:
a[0, 2, 1]

5

In [19]:
b = a.transpose(1, 2, 0)
b.shape

(3, 2, 4)

In [20]:
b[2, 1, 0]

5

In [21]:
b[2, 1, 0] = -1
a[0, 2, 1]

-1

In [22]:
a = np.arange(4)
a.resize((8,))
a

array([0, 1, 2, 3, 0, 0, 0, 0])

In [23]:
b = a
a.resize((4,))  

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False